const swaggerAutogen = require('swagger-autogen')();

// Basic API metadata for the generated docs.
//
// NOTE: the schemas live under '@definitions' on purpose. swagger-autogen
// runs every entry of 'definitions' through a type-inference pass that
// rewrites proper JSON Schema into sample-data form. Anything registered under
// '@definitions' is merged in after that pass and is left untouched.
const doc = {
    info: {
        title: 'Contacts API',
        description: 'REST API to create, read, update and delete contacts stored in MongoDB.',
        version: '1.0.0',
    },
    host: 'project01-bk00.onrender.com',
    basePath: '/',
    schemes: ['https'],
    tags: [
        {
            name: 'Home',
            description: 'Base route of the Contacts API',
        },
        {
            name: 'Contacts',
            description: 'CRUD operations on the contacts collection',
        },
    ],
    '@definitions': {
        ContactInput: {
            description: 'The five fields required to create or replace a contact. The _id is generated by MongoDB and must not be sent.',
            type: 'object',
            required: ['firstName', 'lastName', 'email', 'favoriteColor', 'birthday'],
            properties: {
                firstName: { type: 'string', example: 'Sofia' },
                lastName: { type: 'string', example: 'Ramirez' },
                email: { type: 'string', example: 'sofia.ramirez@example.com' },
                favoriteColor: { type: 'string', example: 'purple' },
                birthday: { type: 'string', example: '1998-04-12' },
            },
        },
        Contact: {
            description: 'A stored contact, including the _id that MongoDB assigned on insert.',
            type: 'object',
            required: ['firstName', 'lastName', 'email', 'favoriteColor', 'birthday'],
            properties: {
                _id: {
                    type: 'string',
                    description: 'Assigned by MongoDB when the contact is created. Not sent by the client.',
                    example: '6ab6bd0406634384d69bc582',
                },
                firstName: { type: 'string', example: 'Sofia' },
                lastName: { type: 'string', example: 'Ramirez' },
                email: { type: 'string', example: 'sofia.ramirez@example.com' },
                favoriteColor: { type: 'string', example: 'purple' },
                birthday: { type: 'string', example: '1998-04-12' },
            },
        },
        ContactList: {
            description: 'A list of stored contacts.',
            type: 'array',
            items: { $ref: '#/definitions/Contact' },
        },
        ContactId: {
            description: 'The _id of a newly created contact, assigned by MongoDB.',
            type: 'object',
            properties: {
                _id: { type: 'string', example: '6ab6bd0406634384d69bc582' },
            },
        },
    },
};

// Generate swagger.json from the routes.
const outputFile = './swagger.json';
const endpointsFiles = ['./routes/index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
